### ISSUE TITLE
การใช้งาน NeoPixel 

### ISSUE THREAD

**Issue by inexglobal** [MakerAsia/ipst-wifi-board#2]
![NeoPixel_KBIDE](https://user-images.githubusercontent.com/37691139/60802144-7e76ce80-a1a2-11e9-819d-cf319efe66fe.jpg)
ทุกครั้งที่มีการลากบล็อก NeoPixel  จะเกิด Error  ใช้  KBIDE win32.exe

`Unhandled Error
TypeError: Cannot read property 'call' of undefined
    at Blockly.Generator.blockToCode (app://./js/chunk-vendors.3c639d10.js:1679:942530)
    at Blockly.Generator.workspaceToCode (app://./js/chunk-vendors.3c639d10.js:1679:941740)
    at VueComponent.updatecode (app://./js/app.d520568f.js:1:146049)
    at Blockly.WorkspaceSvg.Blockly.Workspace.fireChangeListener (app://./js/chunk-vendors.3c639d10.js:1679:665983)
    at Blockly.Events.fireNow_ (app://./js/chunk-vendors.3c639d10.js:1679:642902)`

**Comment by bavensky** [comment]
สวัสดีครับ ตอนนี้ได้ทำการ publish board เวอร์ชั่น 1.0.0 รบกวนไปยัง Board Manager ในส่วน Online available แล้วทำการติดตั้งไปยังโปรแกรม และรบกวนทดสอบได้เลยครับ กรณีมีปัญหา จะดำเนินการแก้ไข และอัพเดทเป็นเวอร์ชั่นต่อไปครับ ขอบคุณครับ
![image](https://user-images.githubusercontent.com/6897546/60943956-b5b7bd80-a311-11e9-9a6e-043f9ab7b9a8.png)
